# Spring properties
spring:
   application:
      name: zssn-server
   datasource:
      username: sa
      password: 
      url: jdbc:h2:mem:test;MODE=MySQL;DB_CLOSE_ON_EXIT=FALSE
      driverClassName: org.h2.Driver
   jpa:
      hibernate:
         ddl-auto: create
      database: H2
      show-sql: true 

# HTTP settings
server:
   port: 8080